import { Box, Typography, Chip } from '@mui/material'
import { Download } from 'lucide-react'
import { useTranslation } from 'react-i18next'
import { AdvancedDataGrid } from '@/components/data-grid/AdvancedDataGrid'
import { useToast } from '@/components/feedback/ToastProvider'
import { reportsApi } from '../api/reports-api'
import type { Report, ReportType } from '../types/report'
import type { ColumnDef, RowMenuItem } from '@/components/data-grid/types'

const typeColor: Record<ReportType, 'default' | 'info' | 'success'> = {
  financial: 'success',
  operational: 'info',
  client: 'default',
}

const typeOptions = [
  { value: 'financial', label: 'Financial' },
  { value: 'operational', label: 'Operational' },
  { value: 'client', label: 'Client' },
]

export function ReportingsListPage() {
  const { t } = useTranslation()
  const { showToast } = useToast()

  const columns: ColumnDef<Report>[] = [
    { field: 'name', headerName: 'Report', sortable: true },
    {
      field: 'type',
      headerName: 'Type',
      sortable: true,
      renderCell: (row) => <Chip size="small" label={row.type} color={typeColor[row.type]} />,
    },
    { field: 'generatedBy', headerName: 'Generated by' },
  ]

  const rowMenuItems: RowMenuItem<Report>[] = [
    { label: 'Download', icon: <Download size={16} />, onClick: (row) => showToast(`Downloading ${row.name} (demo)`, 'info') },
  ]

  return (
    <Box>
      <Typography variant="h5" sx={{ fontWeight: 700, mb: 2 }}>
        {t('nav.reportings')}
      </Typography>

      <AdvancedDataGrid<Report>
        queryKey="reportings"
        fetchFn={reportsApi.list}
        columns={columns}
        filters={{
          fields: [
            { name: 'name', label: 'Report', type: 'text' },
            { name: 'type', label: 'Type', type: 'select', options: typeOptions },
          ],
        }}
        rowActions={{ items: rowMenuItems }}
        toolbar={{ showRefresh: true }}
      />
    </Box>
  )
}
